#!/bin/bash
# Git commit helper functions for UBL history building
# Source this file after common.sh

# Ensure common.sh is loaded
if [[ -z "${REPO_ROOT:-}" ]]; then
    echo "ERROR: common.sh must be sourced before commit-helpers.sh" >&2
    exit 1
fi

# Session URL for commit messages
readonly SESSION_URL="https://claude.ai/code/session_01DootdmjSDVpY6qQJprMW84"

# Initialize history branch (creates orphan branch with initial commit)
init_history_branch() {
    local branch="$1"

    log_step "Initializing history branch: $branch"

    # Check if branch already exists
    if git rev-parse --verify "$branch" &>/dev/null; then
        log_warning "Branch $branch already exists"
        read -p "Delete and recreate? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git branch -D "$branch" || die "Failed to delete existing branch"
        else
            die "Cannot proceed with existing branch"
        fi
    fi

    # Create orphan branch (no history)
    git checkout --orphan "$branch" || die "Failed to create orphan branch"

    # Remove all files from staging
    git rm -rf . 2>/dev/null || true

    # Create initial README
    cat > README.md <<'EOF'
# UBL GenericCode Evolution History

This branch contains the complete evolution of UBL GenericCode semantic model files from UBL 2.0 (2006) through UBL 2.5 (2025).

## About This Branch

- **Purpose:** Git-based version control of UBL semantic models
- **Coverage:** 35 releases across UBL 2.0-2.5
- **Files Tracked:** UBL-Entities, UBL-Signature-Entities, UBL-Endorsed-Entities
- **Generated By:** Reproducible build scripts in main branch

## How to Use

```bash
# View complete history
git log --oneline --graph

# See evolution of a specific file
git log --follow UBL-Entities-2.1.gc

# Compare versions
git diff <commit1> <commit2> UBL-Entities-2.1.gc

# Checkout a specific version
git checkout <commit> UBL-Entities-2.1.gc
```

## Files at Each Version

At each commit, this branch contains the GenericCode files for that specific release stage:
- `UBL-Entities-{version}.gc` - Main semantic model
- `UBL-Signature-Entities-{version}.gc` - Digital signature entities (when available)
- `UBL-Endorsed-Entities-{version}.gc` - Endorsed subset (UBL 2.5 only)

## Reproducibility

This branch is generated by scripts in the main branch:
- `scripts/build-history.sh` - Master orchestrator
- `scripts/versions/build-2.*.sh` - Version-specific builders

To rebuild this branch:
```bash
git checkout main
./scripts/build-history.sh
```

## Source Data

All source files are in the main branch under `history/`:
- `history/generated/*-UBL-2.0/` - UBL 2.0 GenericCode (generated from .ods)
- `history/*-UBL-2.1/` through `history/*-UBL-2.5/` - OASIS releases

See main branch README.md for complete documentation.
EOF

    git add README.md
    git commit -m "Initial commit: UBL history branch

This branch tracks the evolution of UBL GenericCode semantic models
across 35 releases from UBL 2.0 (2006) through UBL 2.5 (2025).

Generated by reproducible build scripts in main branch.

$SESSION_URL"

    log_success "History branch initialized: $branch"
}

# Create a simple release commit (copies files and commits)
create_release_commit() {
    local release="$1"        # e.g., "prd-UBL-2.0"
    local version="$2"        # e.g., "2.0"
    local release_dir="$3"    # Full path to release directory
    local commit_message="$4" # Custom commit message (optional)

    log_step "Creating commit for $release"

    # Verify release directory exists
    check_dir_exists "$release_dir"

    # Get GenericCode files for this release
    local gc_files
    mapfile -t gc_files < <(get_gc_files "$release_dir" "$version")

    if [[ ${#gc_files[@]} -eq 0 ]]; then
        die "No GenericCode files found in $release_dir"
    fi

    # Verify all files
    local all_valid=true
    for gc_file in "${gc_files[@]}"; do
        if ! verify_gc_file "$gc_file"; then
            all_valid=false
        fi
    done

    if [[ "$all_valid" != "true" ]]; then
        die "Some GenericCode files failed validation"
    fi

    # Copy files to working directory
    for gc_file in "${gc_files[@]}"; do
        local basename
        basename=$(basename "$gc_file")
        cp "$gc_file" "$basename"
        git add "$basename"
        log_info "Added: $basename ($(count_gc_rows "$gc_file") rows)"
    done

    # Generate commit message if not provided
    if [[ -z "$commit_message" ]]; then
        local stage_name
        stage_name=$(get_stage_name "$release")
        local stage_desc
        stage_desc=$(get_stage_description "$stage_name")

        commit_message="UBL $version - $stage_name ($stage_desc)

Release: $release
Files: ${#gc_files[@]} GenericCode file(s)
"

        # Add file details
        for gc_file in "${gc_files[@]}"; do
            local basename
            basename=$(basename "$gc_file")
            local row_count
            row_count=$(count_gc_rows "$gc_file")
            commit_message+="- $basename: $row_count rows
"
        done

        commit_message+="
Source: history/$release/ (OASIS official release)

$SESSION_URL"
    fi

    # Create commit
    git commit -m "$commit_message" || die "Failed to create commit for $release"

    log_success "Commit created for $release"
}

# Create a schema transition commit (multi-step: add columns)
create_schema_add_columns_commit() {
    local from_version="$1"
    local to_version="$2"
    local new_columns="$3"  # Comma-separated list of new column names

    log_step "Schema transition step 1/6: Add new columns ($from_version → $to_version)"

    # For now, this is a placeholder - actual schema manipulation would require
    # parsing and modifying the XML structure
    log_info "Adding columns: $new_columns"

    # TODO: Implement actual XML manipulation
    # For now, we'll document the change in the commit message

    local commit_message="UBL $from_version → $to_version: Add new columns (empty)

Schema Evolution Step 1 of 6: Column Addition

New columns added (initially empty):
$(echo "$new_columns" | tr ',' '\n' | sed 's/^/- /')

These columns will be populated in the next commit.

$SESSION_URL"

    # Since we're not actually modifying files yet, just create a commit message placeholder
    log_warning "Schema manipulation not yet implemented - skipping for now"
}

# Create a batch of release commits for a version
create_version_commits() {
    local version="$1"       # e.g., "2.0"
    local base_dir="$2"      # "generated" or "."
    shift 2
    local releases=("$@")    # Array of release names

    log_step "Creating commits for UBL $version (${#releases[@]} releases)"

    for release in "${releases[@]}"; do
        local release_dir
        release_dir=$(get_release_dir "$release" "$base_dir")

        create_release_commit "$release" "$version" "$release_dir"
    done

    log_success "Completed all commits for UBL $version"
}

# Get commit date from release metadata (or use current date)
get_release_date() {
    local release="$1"

    # TODO: Extract actual release dates from OASIS metadata
    # For now, use current date
    date -R
}

# Export functions
export -f init_history_branch create_release_commit
export -f create_schema_add_columns_commit create_version_commits
export -f get_release_date
